= Exercises 4

== Exercise 25
Write a query to return the first 50 documents for gold medal athletics events, in descending age order.

금메달 육상 경기(athletics events)의 처음 50개 문서를 내림차순으로 반환하는 쿼리를 작성합니다.

== Exercise 26
Write a query to match swimming events where either:

- The athlete's weight was between 60kg and 70kg
- The athlete's age was less than 20

Enhance the query so the results identify whether the weight, age, or both matched the search criteria.

다음 중 하나에 해당하는 수영 이벤트와 일치하는 쿼리를 작성합니다.

- 선수의 체중은 60kg에서 70kg 사이였습니다
- 선수의 나이는 20 세 미만이었습니다

결과가 체중, 연령 또는 둘 다 검색 기준과 일치하는지 여부를 식별할 수 있도록 쿼리를 개선합니다.

== Exercise 27
Download the file of National Olympic Committees from here and use Kibana’s Data Visualizer to import the data into a new index called olympic-noc-regions.

== Exercise 28
Change the number of replica shards for the olympic-noc-regions index to be 0. The index should then be green and contain 230 documents.

== Exercise 29
Create an enrich policy and ingest pipeline that uses the enrich processor to add details of the National Olympic Committee to each document in the olympic-events-fixed index. Call the policy olympic-noc-append and the pipeline enrich-noc. Add details of the matching NOC entry to a new field called nocDetails, matching on the noc field.

== Exercise 30
Create a new index called olympic-events-enriched, into which we can reindex the Olympic events but with some enriched fields. Change the mapping settings for the new index so we can add fields dynamically.

== Exercise 31
Reindex the olympic-events-fixed index into olympic-events-enriched, running it through the enrich-noc ingest pipeline. Once complete, verify the new field was added to the olympic-events-fixed index, and populated with details of the associated NOC.